---
title: 'Assignment 1: Introduction'
author: 'Leo Zhang'
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change 'Student Name' on line 3 (above) with your name.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.

7.  Initial here to acknowledge that you did not use AI at all in completing this assignment: LZ

---

## 1) Concept and Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have taken ENVIRON 710. During my undergraduate period, I learned the fundamental skills about Python, SQL, Neo4j, and MongoDB. My Github account was created in 2023.


2. Are there any components of the course about which you feel confident?

> Answer: I have prior experience in RStudio. In addition, flexibility resulting from the hybrid format is beneficial.


3. Are there any components of the course about which you feel apprehensive?

> Answer: Given my health, I don't know whether I can collaborate smoothly for the final project.


4. Describe a dataset you have used in the past. Explain whether it was a primary or secondary dataset. 

> Answer: Fragile States Index (FSI) is published annually by The Fund For Peace. Measuring the socioeconomic development of countries, it is a number between 0 and 120. While 0 indicates the least fragility, 120 indicates the most fragility. I adopted FSI to explore the relationship between ecological and socioeconomic wellness. Therefore, I regarded FSI as a secondary dataset.


5. Would you describe the day of the month as a nominal, ordinal, interval, or ratio number? Explain your reasoning.

> Answer: It is an ordinal number. The order of dates is meaningful. However, the day numbers do not represent magnitude.


---

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/leozhangzzgx/872_spring26


---

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 

